### ISSUE TITLE
Matrix Please

### ISSUE THREAD

**Issue by JayDee696969** [michaelfdeberry/plugin.audio.datpiff#4]
Can you please make Matrix compatible? Thank you!!

**Comment by michaelfdeberry** [comment]
I looked into it, supporting Matrix will require a rewrite. It's a small plugin, so it wouldn't take long to do, but I am not sure when I would be able to get to it.

**Comment by michaelfdeberry** [comment]
That didn't take as long as I thought, let me know if you have any issues
